
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 35;
  public static final int DIVIDE = 14;
  public static final int CONCAT = 4;
  public static final int POOL = 52;
  public static final int INTEGER = 29;
  public static final int NOTEQUAL = 7;
  public static final int LPAREN = 23;
  public static final int GREATER = 18;
  public static final int FOR = 54;
  public static final int LESS = 17;
  public static final int MINUS = 12;
  public static final int CHARACTER = 30;
  public static final int RPAREN = 24;
  public static final int NOT = 10;
  public static final int SEMICOLON = 2;
  public static final int AND = 8;
  public static final int RATIONAL = 31;
  public static final int LESSEQUAL = 16;
  public static final int ILLEGAL_CHARACTER = 59;
  public static final int IN = 41;
  public static final int TDEF = 38;
  public static final int OR = 9;
  public static final int COMMA = 19;
  public static final int UPTO = 53;
  public static final int FI = 44;
  public static final int THREAD = 36;
  public static final int LOOP = 51;
  public static final int PLUS = 11;
  public static final int IF = 43;
  public static final int MAIN = 37;
  public static final int ASSIGN = 3;
  public static final int CARET = 21;
  public static final int DOT = 22;
  public static final int EOF = 0;
  public static final int BOOLEAN = 33;
  public static final int RETURN = 49;
  public static final int EQUAL = 6;
  public static final int error = 1;
  public static final int NUMBER = 57;
  public static final int BREAK = 50;
  public static final int FDEF = 39;
  public static final int OFRANGE = 55;
  public static final int IMPLY = 15;
  public static final int TOP = 40;
  public static final int LBRACK = 27;
  public static final int TIMES = 13;
  public static final int COLON = 5;
  public static final int ELSE = 46;
  public static final int DICT = 34;
  public static final int LBRACE = 25;
  public static final int READ = 47;
  public static final int RBRACK = 28;
  public static final int FLOAT = 32;
  public static final int THEN = 45;
  public static final int RBRACE = 26;
  public static final int STRING = 58;
  public static final int QUESTION = 20;
  public static final int ALIAS = 42;
  public static final int PRINT = 48;
  public static final int IDENTIFIER = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "ASSIGN",
  "CONCAT",
  "COLON",
  "EQUAL",
  "NOTEQUAL",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "IMPLY",
  "LESSEQUAL",
  "LESS",
  "GREATER",
  "COMMA",
  "QUESTION",
  "CARET",
  "DOT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "INTEGER",
  "CHARACTER",
  "RATIONAL",
  "FLOAT",
  "BOOLEAN",
  "DICT",
  "SEQ",
  "THREAD",
  "MAIN",
  "TDEF",
  "FDEF",
  "TOP",
  "IN",
  "ALIAS",
  "IF",
  "FI",
  "THEN",
  "ELSE",
  "READ",
  "PRINT",
  "RETURN",
  "BREAK",
  "LOOP",
  "POOL",
  "UPTO",
  "FOR",
  "OFRANGE",
  "IDENTIFIER",
  "NUMBER",
  "STRING",
  "ILLEGAL_CHARACTER"
  };
}

